### ISSUE TITLE
Installing indexer fails due to missing file

### ISSUE THREAD

**Issue by robliou** [EdgeDLT/shrike#1]
Hi @EdgeDLT ! 

I just attempted to install the Shrike Indexer into my Windows 10 machine. I followed the directions to a T, including downloading and installing Rustup, and downloading NeoGo, renaming it, and putting it into the Indexer root folder. 

After running the command cargo run --release in the Indexer root folder, I get the following error: 

![bug01272023](https://user-images.githubusercontent.com/81087205/215008400-67dfabdb-1dec-4668-83d7-6306088cf5f3.png)

Supposedly, this file is missing: "shrike-indexer\src\spawn.rs:34:14"

Have you come across this error? If so, any ideas how to fix it?

Thanks,

**Comment by edgedlt** [comment]
Hey @robliou, thanks for your report! Seems like it's just not finding the binary for some reason.

NEOGO_PATH is currently set on line 19 in `main.rs.` By default it should be `./neogo.exe`, which points to `neogo.exe` in the `shrike-indexer` folder. 

Can you confirm the NEOGO_PATH and file path for `neogo.exe` for me?

EDIT: I notice in the directions I wasn't very explicit about which `Cargo.toml` file you should be putting the binary next to. Make sure it's the one in `shrike-indexer`, there is also a different `Cargo.toml` for `shrike` and `shrike-api` respectively.

**Comment by robliou** [comment]
Hi @EdgeDLT , using your method I can see where my error is! Basically, when I renamed the neogo.exe file, it accidentally renamed to "neogo.exe.exe." Hence, this caused the "file is missing" error. Thanks!

OK, so moving forward, a few more questions:

1) Running the indexer, it appears that the block data is added incrementally as multiple ".ldb" files to my ./shrike/shrike-indexer/ chains/mainnet folder. Quite nice. 

However, is all of this data forward-looking, only? Does it include historical data, and if not, how would I access that?

2) Per the instructions of step #2 of the shrike/API Quickstart, it says to "Get a copy of the Shrike DB from the download page (TODO) or by running the Indexer." 

Given that each block update is coming as a separate file, what is the "copy of the Shrike DB" referring to? I see a "shrike.db3" file in the root folder of the indexer, but it is just 24kb, and doesn't look to be updating?

Thanks,

**Comment by edgedlt** [comment]
Glad to hear you're up and running!

As you noted, the `chains` folder stores the actual blockchain data from genesis to the current synced node height. This is created by NeoGo and is used for its internal operations. So it does contain historic data, but it's awkward to query it via the RPC interface as you have no doubt already discovered.

Shrike DB does indeed refer to `shrike.db3`. The DB is created when you first run the Indexer, however it will not begin to index the chain data until your NeoGo instance has reached the current blockchain height. You'll know that has occurred when the Indexer stops outputting the `INFO persisted to disk` messages from NeoGo, followed by `Sync completed in X ms`.

Once NeoGo has caught up to the blockchain height, you should see `shrike.db3` start growing. It should be much faster than the syncing process itself, it takes a little under 15 minutes to fully index MainNet from start to finish on my machine. 

Once done, assuming you aren't running in `keep-alive` mode, the program should terminate itself.

Here's an example output of a full run for comparison:

```
Welcome to Shrike!
Last stored block index: 2877619
Starting node sync..
2023-01-28T10:27:01.799Z        INFO    node started   {"blockHeight": 2877620, "headerHeight": 2877620}

    _   ____________        __________
   / | / / ____/ __ \      / ____/ __ \
  /  |/ / __/ / / / /_____/ / __/ / / /
 / /|  / /___/ /_/ /_____/ /_/ / /_/ /
/_/ |_/_____/\____/      \____/\____/

/NEO-GO:0.101.0/

2023-01-28T10:27:02.812Z        INFO    persisted to disk       {"blocks": 10, "keys": 486, "headerHeight": 2877630, "blockHeight": 2877630, "took": "11.5009ms"}
2023-01-28T10:27:03.846Z        INFO    persisted to disk       {"blocks": 290, "keys": 14931, "headerHeight": 2877920, "blockHeight": 2877920, "took": "45.8789ms"}
2023-01-28T10:27:04.972Z        INFO    persisted to disk       {"blocks": 640, "keys": 21254, "headerHeight": 2878560, "blockHeight": 2878560, "took": "171.3326ms"}
2023-01-28T10:27:05.856Z        INFO    persisted to disk       {"blocks": 627, "keys": 27252, "headerHeight": 2879188, "blockHeight": 2879187, "took": "54.8242ms"}
2023-01-28T10:27:06.845Z        INFO    persisted to disk       {"blocks": 492, "keys": 21574, "headerHeight": 2879679, "blockHeight": 2879679, "took": "43.0584ms"}
Sync completed in 6786 ms.
Chain height is 2879892.
Started indexing.
Start height is 2877620.
2272 blocks to process.
Indexing completed in 1473 ms.
Killing the node now.
```

**Comment by robliou** [comment]
@EdgeDLT Thanks, that makes sense! I'll give this a shot in the next couple days/ weeks. 

If there are any other issues, I'll open a separate issue. So, you can close this one now if you like!

Thanks again!

**Comment by edgedlt** [comment]
Cool. Let me know how it goes and if you have any suggestions.
